/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef VMPROCESSTABLE_H
#define VMPROCESSTABLE_H

/* function declarations */
void init_vmProcessTable(void);
void initialize_table_vmProcessTable(void);
Netsnmp_Node_Handler vmProcessTable_handler;

/* column number definitions for table vmProcessTable */
       #define COLUMN_VMPROCESSPID		1
       #define COLUMN_VMPROCESSOWNER		2
       #define COLUMN_VMPROCESSCPU		3
       #define COLUMN_VMPROCESSMEM		4
       #define COLUMN_VMPROCESSSTATE		5
#endif /* VMPROCESSTABLE_H */
