/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef VMVIDEOTABLE_H
#define VMVIDEOTABLE_H

/* function declarations */
void init_vmVideoTable(void);
void initialize_table_vmVideoTable(void);
Netsnmp_Node_Handler vmVideoTable_handler;

/* column number definitions for table vmVideoTable */
       #define COLUMN_VMVIDEOID		1
       #define COLUMN_VMVIDEOAUDIENCE		2
       #define COLUMN_VMVIDEOADVERTISINGMETRICS		3
       #define COLUMN_VMVIDEOKINDVOD		4
       #define COLUMN_VMVIDEOKINDLIVE		5
#endif /* VMVIDEOTABLE_H */
