/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "vmChannelTable.h"

/** Initialize the vmChannelTable table by defining its contents and how it's structured */
void
initialize_table_vmChannelTable(void)
{
    const oid vmChannelTable_oid[] = {1,3,6,1,4,1,12619,1,4};
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("vmChannelTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_vmChannelTable",
                "adding indexes to table vmChannelTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: vmChannelIndex */
                           0);

    DEBUGMSGTL(("initialize_table_vmChannelTable",
                "adding column types to table vmChannelTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_VMCHANNELINDEX, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_VMCHANNELID, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_VMCHANNELAUDIENCE, ASN_INTEGER, 0,
                                            NULL, 0,
                              0);
    
    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change vmChannelTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("vmChannelTable", vmChannelTable_handler,
                                                        vmChannelTable_oid,
                                                        OID_LENGTH(vmChannelTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}

/** Initializes the vmChannelTable module */
void
init_vmChannelTable(void)
{

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_vmChannelTable();
}

/** handles requests for the vmChannelTable table, if anything else needs to be done */
int
vmChannelTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}
