/*
 * Note: this file originally auto-generated by mib2c using
 *  $
 */
#ifndef VMCHANNELTABLE_H
#define VMCHANNELTABLE_H

/* function declarations */
void init_vmChannelTable(void);
void initialize_table_vmChannelTable(void);
Netsnmp_Node_Handler vmChannelTable_handler;

/* column number definitions for table vmChannelTable */
       #define COLUMN_VMCHANNELINDEX		1
       #define COLUMN_VMCHANNELID		2
       #define COLUMN_VMCHANNELAUDIENCE		3
#endif /* VMCHANNELTABLE_H */
