/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "vmProcessTable.h"

processTable data[20];


/** Initialize the vmProcessTable table by defining its contents and how it's structured */
void
initialize_table_vmProcessTable(void)
{
    const oid vmProcessTable_oid[] = {1,3,6,1,4,1,12619,1,3};
    netsnmp_table_data_set *table_set;

    /* create the table structure itself */
    table_set = netsnmp_create_table_data_set("vmProcessTable");

    /* comment this out or delete if you don't support creation of new rows */
    table_set->allow_creation = 1;

    /***************************************************
     * Adding indexes
     */
    DEBUGMSGTL(("initialize_table_vmProcessTable",
                "adding indexes to table vmProcessTable\n"));
    netsnmp_table_set_add_indexes(table_set,
                           ASN_INTEGER,  /* index: vmProcessIndex */
                           0);

    DEBUGMSGTL(("initialize_table_vmProcessTable",
                "adding column types to table vmProcessTable\n"));		 
    netsnmp_table_set_multi_add_default_row(table_set,
                                            COLUMN_VMPROCESSINDEX, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_VMPROCESSPID, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_VMPROCESSOWNER, ASN_OCTET_STR, 0,
                                            NULL, 0,
                                            COLUMN_VMPROCESSCPU, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_VMPROCESSMEM, ASN_INTEGER, 0,
                                            NULL, 0,
                                            COLUMN_VMPROCESSSTATE, ASN_OCTET_STR, 0,
                                            NULL, 0,
                              0);
    

        int i;
        for (i = 0; i < 20; ++i)
        {
                data[i].pid = rand()%1000;
                data[i].cpu = rand()%100;
                data[i].mem = rand()%1000;
                strcat(data[i].state, "R");
                if (rand()%2 == 1)
                        strcat(data[i].state, "Z");
                strcat(data[i].owner, "bruno");


                netsnmp_table_row* row = netsnmp_create_table_data_row();
		
                netsnmp_table_row_add_index(row, ASN_INTEGER, &i, sizeof(i));
                netsnmp_set_row_column(row, COLUMN_VMPROCESSINDEX, ASN_INTEGER, &i, sizeof(i));
                netsnmp_set_row_column(row, COLUMN_VMPROCESSPID, ASN_INTEGER, &data[i].pid, sizeof(data[i].pid));
                netsnmp_set_row_column(row, COLUMN_VMPROCESSOWNER, ASN_OCTET_STR, data[i].owner, sizeof(data[i].owner));
                netsnmp_set_row_column(row, COLUMN_VMPROCESSCPU, ASN_INTEGER, &data[i].cpu, sizeof(data[i].cpu));
                netsnmp_set_row_column(row, COLUMN_VMPROCESSMEM, ASN_INTEGER, &data[i].mem, sizeof(data[i].mem));
                netsnmp_set_row_column(row, COLUMN_VMPROCESSSTATE, ASN_OCTET_STR, data[i].state , sizeof(data[i].state));
                netsnmp_table_dataset_add_row(table_set, row);
        }

    /* registering the table with the master agent */
    /* note: if you don't need a subhandler to deal with any aspects
       of the request, change vmProcessTable_handler to "NULL" */
    netsnmp_register_table_data_set(netsnmp_create_handler_registration("vmProcessTable", vmProcessTable_handler,
                                                        vmProcessTable_oid,
                                                        OID_LENGTH(vmProcessTable_oid),
                                                        HANDLER_CAN_RWRITE),
                            table_set, NULL);
}

/** Initializes the vmProcessTable module */
void
init_vmProcessTable(void)
{

  /* here we initialize all the tables we're planning on supporting */
    initialize_table_vmProcessTable();
}

/** handles requests for the vmProcessTable table, if anything else needs to be done */
int
vmProcessTable_handler(
    netsnmp_mib_handler               *handler,
    netsnmp_handler_registration      *reginfo,
    netsnmp_agent_request_info        *reqinfo,
    netsnmp_request_info              *requests) {
    /* perform anything here that you need to do.  The requests have
       already been processed by the master table_dataset handler, but
       this gives you chance to act on the request in some other way
       if need be. */
    return SNMP_ERR_NOERROR;
}
