/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef VMPROCESSCOUNT_H
#define VMPROCESSCOUNT_H

/* function declarations */
void init_vmProcessCount(void);
Netsnmp_Node_Handler handle_vmProcessCount;

#endif /* VMPROCESSCOUNT_H */
