/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */

#include <net-snmp/net-snmp-config.h>
#include <net-snmp/net-snmp-includes.h>
#include <net-snmp/agent/net-snmp-agent-includes.h>
#include "vmProcessCount.h"

int processcount = 0;
const char* swapfile = "/tmp/pcount";

/** Initializes the vmProcessCount module */
void
init_vmProcessCount(void)
{
    const oid vmProcessCount_oid[] = { 1,3,6,1,4,1,12619,1,2 };

  DEBUGMSGTL(("vmProcessCount", "Initializing\n"));

    netsnmp_register_scalar(
        netsnmp_create_handler_registration("vmProcessCount", handle_vmProcessCount,
                               vmProcessCount_oid, OID_LENGTH(vmProcessCount_oid),
                               HANDLER_CAN_RWRITE
        ));
    
    FILE* fp = fopen(swapfile, "r");
    if (fp) {
        int params = fscanf(fp, "%d", &processcount);
        (void)params;
    }
    fclose(fp); 


}

int
handle_vmProcessCount(netsnmp_mib_handler *handler,
                          netsnmp_handler_registration *reginfo,
                          netsnmp_agent_request_info   *reqinfo,
                          netsnmp_request_info         *requests)
{
    int ret;
    /* We are never called for a GETNEXT if it's registered as a
       "instance", as it's "magically" handled for us.  */

    /* a instance handler also only hands us one request at a time, so
       we don't need to loop over a list of requests; we'll only get one. */
    FILE* fp; 
    switch(reqinfo->mode) {

        case MODE_GET:
	    fp = fopen(swapfile, "r");
	    if (fp) {
		int params = fscanf(fp, "%d", &processcount);
		(void)params;
	    }
	    fclose(fp); 
            
	    snmp_set_var_typed_value(requests->requestvb, ASN_INTEGER,
                                     &processcount,
                                     sizeof(processcount));
            break;

        /*
         * SET REQUEST
         *
         * multiple states in the transaction.  See:
         * http://www.net-snmp.org/tutorial-5/toolkit/mib_module/set-actions.jpg
         */
        case MODE_SET_RESERVE1:
                /* or you could use netsnmp_check_vb_type_and_size instead */
            ret = netsnmp_check_vb_type(requests->requestvb, ASN_INTEGER);
            if ( ret != SNMP_ERR_NOERROR ) {
                netsnmp_set_request_error(reqinfo, requests, ret );
            }
            break;

        case MODE_SET_RESERVE2:
	    break;
        case MODE_SET_FREE:
            break;

        case MODE_SET_ACTION:
            processcount = *(requests->requestvb->val.integer);
	    
	    fp = fopen(swapfile, "w");
	    if (fp) {
		fprintf(fp, "%d", processcount);
	    }
	    fclose(fp); 
            break;

        case MODE_SET_COMMIT:
            break;

        case MODE_SET_UNDO:
            netsnmp_set_request_error(reqinfo, requests, SNMP_ERR_UNDOFAILED);
            break;

        default:
            /* we should never get here, so this is a really bad error */
            snmp_log(LOG_ERR, "unknown mode (%d) in handle_vmProcessCount\n", reqinfo->mode );
            return SNMP_ERR_GENERR;
    }
    return SNMP_ERR_NOERROR;
}
