/*
 * Note: this file originally auto-generated by mib2c using
 *        $
 */
#ifndef VMUPTIME_H
#define VMUPTIME_H

/* function declarations */
void init_vmUptime(void);
Netsnmp_Node_Handler handle_vmUptime;

#endif /* VMUPTIME_H */
